//DOM
var currentText = document.getElementsByTagName("textarea")[0];
var newText =
    "ACCEPTING, BEAUTY IN ALL THINGS, ACTION, BADASSERY, ACTIVATE, BETTER-THAN-EXPECTED, BEYOND THANK YOU, ACTIVE, ADORABLE, ADVANTAGE, AFFIRM, AGELESS, AGREE, AGREEABLE, ACCOUNTABILITY, ACCOMPLISH, FAIRNESS, FAMILY, FIDELITY, ACCURACY, ACHIEVEMENT, FAITHFUL, FAME, FAVORITE, LUSTROUS COLORS, LIGHT-HEARTED, LEEWAY, LET GO, ACKNOWLEDGEMENT, ADAPTABILITY, ADVENTUROUS, AGILITY, ALERTNESS, LIVES THROUGH, LOVE WORDS, LOVER OF BEAUTY BEING AT REST, BENEFACTOR, BENEFITS, AMBITION, ANTICIPATION, APPRECIATIVENESS, ASSERTIVE, RECOGNIZE, RELEASING, RIGHTFUL, ROCKSTAR, ATTENTIVENESS, AUDACITY, AWARE, AUTHENTIC, ABRACADABRA, ATTRACTION, ALLOWING, AFFECTION, BE HAPPY, BEAUTIFY, FLEXIBILITY, FOCUS, FLOURISH, FORGIVE – FORGIVING – FORGIVENESS, FORTITUDE, FREE – FREEDOM, FRUGALITY, FUN, FUTURE, FRIEND – FRIENDLY  LOYAL, LOVE – LOVABLE – LOVING, LIBERTY, LOGIC, LEADER – LEADERSHIP, LUCK – LUCKY, LIGHT, LOVING-KINDNESS, LIVELY, LIFE OF THE PARTY, LOVELY, LOVING ACCEPTANCE, LOVING FEELINGS, LIGHTWORKER, LEADING, LIGHT FOG, BENEVOLENCE, BENEVOLENTLY, BENEVOLENTLY CHEERFUL STATE OF MIND, BEST OF ALL POSSIBLE WORLDS, BEYOND, BEAUTY IN ALL THINGS, BEINGNESS, BELIEVABLE, BLOOD-BROTHERS, BOHEMIAN SOUL, BOHO-SOUL, BADASSERY, BEST-SELLING, BETTER AND BETTER, BETTER-THAN-EXPECTED – FRIENDSHIP, FASCINATE – FASCINATED, FULFILL – FULFILLED, FOOD, FEISTY, FEASIBLE, FINE, FEARLESS, FESTIVE – FESTIVENESS, FIT, FANTABULOUS, FREECYCLE, FUNERIFIC, FUNOLOGY, FLAWLESS, FAMOUS, FANCY, FLASHY, FTW, FUNNY JOKES, FLAUNTING, FONDLE, FRIC-TIONLESSLY, FLAWLESS GLOW, GENEROUS – GENEROSITY, GENERATE, GENIAL, GENIUS, GENUINE, FABULOUS, FAIR, FAITH, , OPTIMIST – PEN HEARTED, OVERCOME, OM MANI PADME HUM, OUTGOING, ONENESS, OUTERNATIONALIST, OVERLY OPTIMISTIC, ORENDA, OWNING YOUR POWER RESPECT, RADIANT, READY – READINESS, REAL – REALITY, REASON, RECOMMEND, REFRESH – REFRESHED, RELAX – RELAXED, RELIEF, REMARKABLE, RATIONALITY, RECOGNITION, RELATIONSHIPS, RELIABILITY, RELIGION, RESOURCEFULNESS, RESPONSIBILITY, RIGHTEOUSNESS, RISK-TAKING, ROMANCE, REVELATION, REVIVED, RESTORE, RESTED, RENEW, REJUVENATED, RAPTUROUS, RESILIENT, REVERENCE, RIPE, REBORN, RELATEDNESS, RASASVADA, REPOSE, ROSINESS, RELENT, RENOWNED, RESPECTED, RAINBOW, ROMANTIC, RELENT, RENOWNED, GIFT, GIVE – GIVING, GOOD, GOODNESS, GOING THE EXTRA MILE, GRACE, GRATITUDE – GRATEFULNESS, GROW – GROWTH, GUIDANCE, GROUNDED, GLORY, GOOD-FEELING, GROOVY LIKE, LAUGH, LEARN, LIFE, LIVING, LONGEVITY, LOYALTY, BEST OF ALL POSSIBLE WORLDS, BEYOND, BEINGNESS, BELIEVABLE, BLOOD-BROTHERS, BOHEMIAN SOUL, BOHO-SOUL, BEST-SELLING, BETTER AND BETTER, BETTER-KNOWN, BIG VISION, BLITHESOME, BLOSSOMING, FANTASTIC, FEEL GOOD – FEELING GOOD, FLOWING, RADIATE";

console.log(newText.length);

currentText.addEventListener("input", function() {
    var input = currentText.value;
    var replacer = "";

    for (var i = 0; i < input.length; i++) {
        replacer += newText[i];
    }

    currentText.value = replacer;
});
